services:
  mongo:
    image: mongo:7
    container_name: warhammer-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: warhammer
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: